title: Ajitesh Singh
description: Personal blog
author: Ajitesh Singh
email: ajiteshjs@gmail.com
url: "https://ajiteshsingh.github.io"

theme: minima
markdown: kramdown
timezone: America/Los_Angeles

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
exclude:
  - README.md
